### PR TITLE
added useful padding feature and improved rendering

### PR DESCRIPTION
**Pull request by vavrecan**

### CODE REVIEW

**Comment by neocotic** [comment]
Could you please open pull requests against the `develop` branch instead of `master`. After that's done I'll be happy to take a look at your changes.

**Comment by vavrecan** [comment]
The feature is simple - create QR codes that fits into specific image size, without padding (or with custom).
I will be busy, do you think you could do the diff and transfer the changes to the develop branch? Thanks! :+1:

**Comment by neocotic** [comment]
I'm quite busy as well, sadly, but I'll try to find some time this week to take a look at the changes and maybe get a minor fix version released for this as well as #55.

**Comment by neocotic** [comment]
I've taken what I think was needed from your changes and included them in the just-released version 2.1.0.

Please check it out and let me know how you find it and raise any bugs that you find.

**Pull request closed without merging**
